### ISSUE TITLE
AddNodeToSubset

### ISSUE THREAD

**Issue by cmungall** [INCATools/kgcl#61]
```
runoak --stacktrace -i simpleobo:tests/input/go-nucleus.obo apply "add GO:0005635 to subset goslim_agr" -o z
Traceback (most recent call last):
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/bin/runoak", line 6, in <module>
    sys.exit(main())
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cjm/repos/ontology-access-kit/src/oaklib/cli.py", line 5699, in apply
    change = kgcl_parser.parse_statement(command)
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/kgcl_schema/grammar/parser.py", line 137, in parse_statement
    raise NotImplementedError("No implementation for KGCL command: " + command)
NotImplementedError: No implementation for KGCL command: add_to_subset
```

**Comment by cmungall** [comment]
done!
